export enum MutationTypes {
    SET_LOADING = 'SET_LOADING',
    UPDATE_FIELD = 'UPDATE_FIELD',
    UPDATE_COUNTRY = 'UPDATE_COUNTRY',
    UPDATE_TOPIC = 'UPDATE_TOPIC',
    FETCH_NEWS = 'FETCH_NEWS',
    FETCH_DETAIL = 'FETCH_DETAIL',
    ADD_FAV = 'ADD_FAV',
    REMOVE_FAV = 'REMOVE_FAV'
}